### ISSUE TITLE
Adapt for etcd2

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#3564]
etcd2 is in the alpha channel now. We'll need to:

- [ ] change some settings in user-data (see https://gist.github.com/carmstrong/c5c4d60c59fbf1558d77)
- [ ] ensure confd supports etcd2
- [ ] support upgrades to etcd 2 from etcd 0.4.x

**Comment by bacongobbler** [comment]
Confd does indeed support etcd2: https://github.com/kelseyhightower/confd/pull/257

**Comment by aledbf** [comment]
@carmstrong create an update procedure? (no provided in alpha)

**Comment by bacongobbler** [comment]
There is an upgrade procedure. `etcd.service` will always refer to etcd1, and `etcd2.service` will be for etcd2. We just need to cut over eventually once it lands in stable :)

**Comment by bacongobbler** [comment]
mailing list announcement: https://groups.google.com/forum/#!topic/coreos-dev/CNGQ49b29BY

**Comment by carmstrong** [comment]
Removing milestone - this likely won't make it into the 1.7 release, as the latest stable promotion does not include etcd2. We'll just remember this issue exists for when we bump to a CoreOS release with etcd2.

**Comment by carmstrong** [comment]
See #3748 for some groundwork on this.

**Comment by aledbf** [comment]
@carmstrong consider the use of dns to bootstrap the cluster and remove the need of the discovery url.

```
_etcd-server._tcp SRV 0 0 2380 deis-01
                  SRV 0 0 2380 deis-02
                  SRV 0 0 2380 deis-03

deis-01   A 172.17.8.100
deis-02   A 172.17.8.101
deis-03   A 172.17.8.102
```
https://github.com/coreos/etcd/blob/master/Documentation/clustering.md#dns-discovery

With this is possible to shutdown the cluster all the times you want and forget the token ttl issues

**Comment by carmstrong** [comment]
@aledbf That's a good idea and would work for those clusters where we know the IPs of the hosts, but I think this would  be blocked by networking V2 and internal service discovery (#3812), right?

**Comment by aledbf** [comment]
@carmstrong no, this works without networking v2. Just etcd2 in CoreOS.

**Comment by carmstrong** [comment]
@aledbf Right, but how do we "discover" the etcd peers initially without a discovery URL? We'd have to know the IPs in advance, right?

**Comment by aledbf** [comment]
@carmstrong I'm sorry. Yes, you need to know the IPs in advance. That's why I mentioned the dns records for the subdomain `local3.deisapp.com`

**Comment by carmstrong** [comment]
> That's why I mentioned the dns records for the subdomain local3.deisapp.com

Right, which I totally get for local clusters. I just mean it won't work for clusters elsewhere until we get internal service discovery of hosts.

**Comment by aledbf** [comment]
>  I just mean it won't work for clusters elsewhere until we get internal service discovery of hosts.

Well if the tool for the internal dns is skydns it will never be possible because it requires etcd :)

I think this could help just in vagrant or those deployments where you know the IPs and can manage the dns service.

**Comment by carmstrong** [comment]
We should also investigate running etcd entirely within a container, so that we're not depending on the version packaged with CoreOS. @kelseyhightower suggested this in our last open roadmap meeting.

**Comment by aledbf** [comment]
I found an issue using etcd2: if some service requires/wants etcd it shutdowns etcd2.
To avoid this I masked the etcd service in cloud-init:
```
  units:
  - name: etcd.service
    mask: true
```

**Comment by carmstrong** [comment]
> if some service requires/wants etcd it shutdowns etcd2.

Good catch. Do you happen to know what requires/wants etcd2? If it's one of our components, we should fix it.

**Comment by aledbf** [comment]
> Do you happen to know what requires/wants etcd2

@carmstrong no and the journal didn't help to find the reason
