### ISSUE TITLE
Proposal: Plan for improving testing of Deisctl

### ISSUE THREAD

**Issue by Joshua-Anderson** [deis/deis#3820]
#### Backend

- [ ] There is a partial fleet stub already done. We should finish the stub and add tests for all fleet operations.

#### Client

- [x] ~~I think we should move the command line parsing from CMD to client, and then call CMD with the parsed values. This will make it easier for us to test the CMD package and separate concerns.~~ #3831

#### CMD

- [x] ~~Currently there is a partial stub of the backend. We should finish this stub and add tests for all the deisctl operations.~~ #3860

#### Config

- [x] ~~ETCD should probably be broken out into its own sub-package. ETCD could be useful out of the config package, for example, for a future `deisctl backup`.~~ I decided against this. ETCD is already easily accessible through the config package. 

- [x] ~~Config has almost no tests. The etcd client could be stubbed or mocked, allowing us to properly test the rest of the config methods.~~ #3859

#### Thoughts

- We have thrown around the idea of moving away from docopt. Whether or not we decide to do that, most of my suggestions should still hold up, we will still need to put more work into mocking and stubbing the backend.

- Mocking vs Stubbing: Currently all the deisctl tests use stubbing on things like fleet and the backend. I think that mocks might be less work than reimplementing the entire backend. I'm not very experienced with go testing, so you guys would know better than I what the best approach would be. 

- This is just stuff I saw and is primarily my own opinion. I'd really like advice on whether these actions make sense or if I missed a area to improve testing.

**Comment by mboersma** [comment]
> I think that testing functions, such as parseArgs, removeGlobalArgs, and isGobalArg directly as opposed to testing output is a better strategy

Agreed. Testing stdout feels out of scope for unit tests, and can be fiddly. 

Also note that the latter two functions are really just there to work around `docopt` behavior, so we don't have to include the global flags again in every subcommand's usage string.

**Comment by technosophos** [comment]
I'm just sort of musing/rambling here... but, for what it's worth...

I agree with the plan in general. I think we could make a few architectural commitments early on that would make life easier over the long run.

**On stderr/stdout:** In general, I agree with your sentiments about not testing output so much as return values. But I think there are also very valid cases for capturing and testing the output. And for that reason, I bet there's a fairly simple alteration we could make that would improve overall design.

I feel it'll be in our best interest to have most of the code write to an `io.Writer` instead of `os.Stdout`, and have the main function pass in os.Stdout/os.Stderr. Long term, that makes it much easier to use code as a library. (Possibly better is to use `log.Logger` and write things to that. The problem with log.Logger is that it doesn't make it easy to write error content to a different writer than non-error content.)

So in the current design, main() would call the runner like this:

```go
os.Exit(Command(argv []string, os.Stdin, os.Stdout)
```

Tests would be able to conveniently capture stdin/stdout data by simply passing in a buffer.Buffer instead of stdout/stderr. You can think of this as sort of simple dependency injection: The outermost environment determines which dependencies inner functions use.

(I am a huge fan of using the io Reader/Writer abstractions whenever possible because you get a ton of flexibility.)

Along these lines, I think we need to get rid of the outchan/errchan channel thing. A writer is a more appropriate thing here than a channel, and honestly we're losing flexibility with the channel handling.

**On mocking vs. stubbing:** One of the cool things about Go is that you can define an interface against an existing API, which has the benefit of making it easy to write very specific stubs/mocks.

Say you have an external library with 20 methods, but you only need to use a few. Define an interface for it, and use that interface in your code. Then, when you go to write tests, you can write mocks against the interface instead of re-implementing the entire external library.

So say our imaginary 3rd party lib has a struct called `SpellChecker`. SpellChecker has, among it's many methods, a Check method that we want to use. That one function checks a string and returns a bool saying whether it's spelled right. That's the only thing we use out of that struct. We can define an interface for this:

```go
type checker interface {
  Check(string) bool
}

// Instead of DoCheck(s string, *c SpellChecker)
func DoCheck(s string, c checker) {
}
```

Then when we write our tests, we just need to mock a `checker`. Of course, the scary part about using interfaces is that you're not supposed to change public interfaces once they're defined. So this is a strategy you have to employ thoughtfully and strategically.

**Comment by carmstrong** [comment]
@Joshua-Anderson Should we consider this closed?

**Comment by Joshua-Anderson** [comment]
Yes. Done!
