### ISSUE TITLE
[meta] Deis v2 Alpha

### ISSUE THREAD

**Issue by slack** [deis/deis#4743]
Meta issue for Deis v2 alpha; as specific issues are filed in other repos, we will link them back to this issue.

## Alpha Goals

Primary goal is to complete the integration of all components necessary for the Deis workflow to function. This includes `git push deis master` with the control plane and data planes running fully within a Kubernetes cluster.

Component pieces of the Deis workflow may be implemented as services that aren't ready for prime time, including single-node, non-ha and non-recoverable. For example, object storage may be off-cluster via S3, Google Storage, or implemented on-cluster as a single-node instance of minio.

Outcome of the alpha will be a concrete set of goals and implementation details for the Beta phase.

## Non-functional requirements

* **Scale target:** none
* **Availability target:** none
* **Recoverability target:** none
* **Dogfooding target:** one internal service, long-running
* **Installation target:** basic case via helm, manual installation ok
* **Infrastructure targets:** AWS via [coreos-kubernetes](https://github.com/coreos/coreos-kubernetes) & GKE

## Meta
* [x] images built and pushed to known location deis/workflow#4
* [x] alpha install instructions documented in deis/workflow#6

### Controller and client: [deis/workflow](https://github.com/deis/workflow)
* [x] deis client cli + lift-and-shift python app

### Database: [deis/postgres](https://github.com/deis/postgres)
* [x] deis/postgres#5

### Etcd: [deis/etcd](https://github.com/deis/etcd)
* [x] deis/etcd#7

### Registry [deis/registry](https://github.com/deis/registry)
* [x] single-instance, no ha: deis/registry#1

### Object storage
* [x] off-cluster: deis/workflow#3
* [x] minio ([deis/minio](https://github.com/deis/minio)) single-instance: deis/minio#1

### Router [deis/router](https://github.com/deis/router)
* [x] basic http routing to services

### Builder [deis/builder](https://github.com/deis/builder)
* `Dockerfile` based pushes not supported for alpha
* [x] basic git-push functionality
    * [slugbuilder](https://github.com/deis/slugbuilder)
    * [slugrunner](https://github.com/deis/slugrunner)
    * git gateway

### Logger
* log aggregation will be addressed in beta

### Monitoring
* monitoring for k8s design doc

**Comment by rimusz** [comment]
sounds good for the alpha release

**Comment by slack** [comment]
Released via deis/charts#54

**Comment by carmstrong** [comment]
> Released via deis/charts#54

:confetti_ball:
