### ISSUE TITLE
[meta] Deis v2 Beta

### ISSUE THREAD

**Issue by slack** [deis/deis#4809]
Meta issue for Deis v2 Beta; as specific issues are filed in other repos, we will link them back to this issue.

[Beta Issues Search](https://github.com/issues?q=is%3Aopen+user%3Adeis+user%3Ahelm+milestone%3Av2.0-beta1+sort%3Aupdated-desc)

## Beta Goals

The Beta period is focused on stabilizing backing services, reaching availability and recoverability targets. Technology choices for each of backing services should be well understood for each of our blessed configurations.

e2e testing infrastructure for v2 platform should be in place. The long-running/soak tests are a requirement to leave beta (see test target below).

Beta should also exit with a strong opinion about production and staging configurations and how best to go from zero to kubernetes.

## Project-level

* [x] Documentation: deis/deis#4889
    * ~~Services that support TLS should be deployed with TLS by default~~
* [x] **Availability target:**
    * Components should be recoverable with manual intervention and documentation
    * Self-healing components where possible
* [ ] **Recoverability target:**
    * Given a backup of the platform, restoring to a known-good k8s cluster should take < 1 hour
* [x] **Infrastructure targets:**
    * Documentation for standup on AWS via [coreos-kubernetes](https://github.com/coreos/coreos-kubernetes)
    * Documentation for standup on GKE
* [x] **Installation target:**
    * Automated via Helm
* [ ] **Test target:**
    * [x] workflow-e2e fully automated
    * [ ] workflow-e2e green
* [x] **Debugging target:**
    * [x] Deis Workflow Manager

## Meta
* [x] all project components adhere to `deis/prototype-repo`
* ~~all components output version information on startup~~
* [x] all components logs available through logging sub-system
* [x] all kubernetes requirements documented (DeamonSets, Versions, etc): deis/deis#4889
* [x] components audited for standard storage layout: deis/deis#4852
* [x] components audited for port usage: deis/deis#4853

## Release Checklist
* [x] update documentation from alpha to beta
* [x] update workflow charts

### Client
* [x] Client v2 master builds pushed to bintray

### Controller [deis/workflow](https://github.com/deis/workflow)
* [x] Django upgrade
* [x] Remove etcd depdendency: deis/workflow#96
* ~~Metrics: expose operational metrics to platform monitor component~~
* Availability
    * [x] Strategy: RC=1
    * [x] Needs health check that hits database: deis/workflow#305
    * [x] Remove etcd interactions: deis/workflow#96

### Database [deis/postgres](https://github.com/deis/postgres)
* [x] Availability
    * [x] Strategy: RC=1
    * [x] Needs health check: deis/postgres#30
    * [x] Wal-e shipping: deis/postgres#31
    * [x] Wal-e backups shipping: deis/postgres#32
    * [ ] Logical backup shipping: deis/postgres#33
* ~~Metrics: expose operational metrics to platform monitor component~~
* [x] Recoverability: documented disaster recovery through backups + restore: deis/postgres#34
* [x] Testing: single node failure, recovery

### ~~Etcd [deis/etcd](https://github.com/deis/etcd)~~
* ~~Availability: HA configuration deployed by default~~
* ~~Metrics: expose operational metrics to platform monitor component~~
* ~~Recoverability: documented backup + restore~~
* ~~Testing: single, multi-node failure, recovery~~

### Registry [deis/registry](https://github.com/deis/registry)
* [x] Availability:
    * [x] Strategy: RC=1
    * [x] Add health check: deis/registry#19
    * [x] Use cluster-configured object storage: deis/registry#20
* ~~Metrics: expose operational metrics to monitor component~~
* [ ] Recoverability: documented backup + restore
* [x] Security: Document that insecure registry must be enabled on kubernetes cluster

### Object storage
* [ ] Off-cluster storage
    * Setup and configuration documented to consume object storage via: (https://github.com/deis/workflow/issues/360)
        * [ ] AWS S3
        * [ ] GCS (in compatability mode)
        * [ ] Ceph Object Storage
    * [ ] `helm generate` works for all of the above scenarios (https://github.com/deis/charts/issues/95)
    * [x] audit and normalize environment variables for all consumers of object storage (ACCESS_KEY, etc.)
        * builder, registry, slugrunner, slugbuilder, postgres/database
* [x] minio [deis/minio](https://github.com/deis/minio)
    * Availability:
        * [x] Strategy: RC=1
        * [x] Add health check: deis/minio#54
    *  ~~SSL/TLS by default~~
    *  Persistent Storage (K8S Volumes/Background Sync)
* ~~RiakCS~~
    * ~~Tested persistent volumes~~

### Router [deis/router](https://github.com/deis/router)
* [x] Router configuration and sub-system documented
* [x] basic http routing to services
* [x] Terminate SSL for workflow/controller
* [x] Terminate SSL for customer applications
* [ ] Metrics: expose operational metrics to monitor component
* Availability
     * Strategy: RC=1 out of box (gives us ssl session resumption)

### Builder [deis/builder](https://github.com/deis/builder)
* [x] `Dockerfile` functionality
* [x] Buildpack functionality
* ~~Metrics: expose operational metrics to monitor component~~
* Availability
    * [x] Strategy: RC=1
    * [x] Needs: health check, should check k8s api service: deis/builder#92
    * [x] Fix user key acquisition: deis/builder#81 deis/builder#122
    * [x] Fix app deletion: https://github.com/deis/builder/issues/167

### Slugbuilder [deis/slugbuilder](https://github.com/deis/slugbuilder)
* [x] Every demo app builds correctly
* ~~Metrics: expose operational metrics to monitor component~~

### Slugrunner [deis/slugrunner](https://github.com/deis/slugrunner)
* ~~Metrics: expose operational metrics to monitor component~~

### Logger [deis/logger](https://github.com/deis/logger)
* [x] Logging sub-system internals documented
* [x] Functioning `deis logs` for all apps
* [x] Platform log-draining + documentation
* Availability:
    * Strategy: RC=1
    * Needs health check: deis/logger#19
    * Does not need to survive restart

### Monitoring [deis/monitor](https://github.com/deis/monitor)
* [ ] Monitor sub-system internals documented
* [ ] Default monitors for workflow components: availability/health only

**Comment by arschles** [comment]
two additional items to consider:

- easing router startup config - it would be nice, from a user & setup perspective, to not have to edit the incoming domain in the router manifest
- port non-Go components of builder to Go

**Comment by slack** [comment]
I agree that the user-experience for folks first setting up the platform would be greatly aided by something which _isn't_ raw k8s wrangling. I feel there is certainly a space for a `deisctl2` type of tool, but I'm on the fence as to what that should be.

Builder can certainly benefit from a non-bash life; however, one of my motivating priorities is working code now, versus the thing we'd like to have. A builder go-rewrite could easily be delivered in a 2.0 point release, which is what I'm leaning toward at the moment. A huge caveat being that through beta, if builder is consistently melting our faces we can reconsider.

**Comment by arschles** [comment]
@slack ok, fair enough. RE the `deisctl2

**Comment by arschles** [comment]
also, @slack we should add persistent storage for minio, under 'object storage'

**Comment by slack** [comment]
Storage added!

**Comment by rimusz** [comment]
:+1:

**Comment by rimusz** [comment]
minio persistent storage example:
```
          volumeMounts:
            - name: home-minio
              mountPath: /home/minio
      volumes:
        - name: home-minio
          hostPath:
            path: /data/deis/minio
```
minio's boot should run `chown minio:minio /home/minio` after `mkdir /home/minio`

**Comment by smothiki** [comment]
Do we need to expose slubuilder metrics exposed ?? After all its an intermittent job that runs and produces slug and dies. 
I think the functionality of buildpack type apps from builder side is done

**Comment by krancour** [comment]
@slack question about the following that was stated WRT router:

> Metrics: expose operational metrics to monitor component

Are any more solid requirements available on what sort of metrics are desired?

**Comment by slack** [comment]
I haven't had the time to pull out specific sets of stats for each of the components. Since we are using prometheus to scrape metrics, a survey of existing prometheus exporters is a great place to start.

In the absence (or even presence) of existing exporters, what we want to enable is operators of the platform to be able to understand the health of the components through these metrics, which then become potential sources for alerts.

To your question @smothiki, emitting metrics for all the platform components lets us answer questions and debug problems with numbers rather than guts. So the more the :chart_with_upwards_trend: :chart_with_downwards_trend: the better.

**Comment by jchauncey** [comment]
Just an update on the metrics side of things. I have a working telegraf/influx setup. So I'm trying to determine what I should do next. If we have the VTS plugin back in the router component then I can take a stab at building a plugin that will scrape those metrics and send them over to our sink. 

For other components we should figure out what is most important and how we want to get that data to influx. 

For example, should we have a /stats endpoint in the controller that prints out metrics in json that we can scrape like we do for router? Or should it just send the metrics to influx as it calculates them?

**Comment by sgoings** [comment]
I'm worried about some of the project level requirements such as:

* [ ] **Test target:**
    * [ ] load test: running for 2 days (24/7) without < 5% dropped requests
    * [ ] load test: 1 deploy/minute across 5 independent applications
    * [x] workflow-e2e fully automated
* [ ] **Dogfooding target:**
    * two Deis internal services, long-running

I know there has been some chatter re: dogfooding, but I have yet to see long running tests of applications and performance/load testing.

**Comment by jchauncey** [comment]
@slack if this is the official document for releasing beta should we remove the metrics requirements from it?

**Comment by slack** [comment]
Yeah, everything but router. Will update.

**Comment by sgoings** [comment]
The final push for v2 beta is visible on #4962
