### ISSUE TITLE
[meta] V2 Beta Documentation Requirements

### ISSUE THREAD

**Issue by slack** [deis/deis#4889]
Meta issue to track items/issues that should be documented for beta/release.

* [x] `ServiceAccount` admission controller required: deis/router#101
  * __Kent edit:__ This turned out to be a red herring for another issue-- improper SSL setup in k8s-- so I think there's nothing new needed in the docs to address this.
* [ ] Liveness / Readiness `config:set` options for applications
* [ ] Documentation for enabling Platform SSL: deis/workflow#332

**Comment by krancour** [comment]
@slack I think deis/router#101 can be fixed faster than it can be documented.

**Comment by slack** [comment]
@krancour yeah, we can work around it in router.

The real goal is to "document our kubernetes expectations," since that is the real issue at hand. Which would also de-couple this ticket from the router.

**Comment by jchauncey** [comment]
Where should this information be documented? In the logger repo I talk about daemonsets - https://github.com/deis/logger#description . 

I also link to the documentation of daemonsets for the logger chart - https://github.com/deis/charts/tree/master/deis-logger

**Comment by jchauncey** [comment]
@slack what is this issue really tracking? should these items be in the main meta issue?

**Comment by slack** [comment]
Meant to hold all the doc ephemera.

At this point, pretty much nothing. I'll close it and move application configuration stuff to docs-v2
