### ISSUE TITLE
[meta] Project reorg before beta

### ISSUE THREAD

**Issue by slack** [deis/deis#4952]
Need to update a few things in the project structure before we cut beta:

1. Move `deis/workflow` to `deis/controller`
    * [x] re-write client go imports to reference `github.com/deis/controller`
    * [x] fixup client build scripts for bintray (if needed)
    * [x] fixup jenkins/travis to push to `deisci/controller`
1. Move `deis/docs-v2` to `deis/workflow` (References deis/docs-v2#23)
1. Update `deis/charts/deis{-dev}` to point to `deis/charts/workflow-{dev}`

/cc @sgoings @helgi

**Comment by helgi** [comment]
Biggest problem I envision from this is the fact we are moving docs into the old workflow. It will confuse things for people if they are not aware of that change where as if docs were not moving into workflow then it would be a far more obvious error.

**Comment by sgoings** [comment]
Better to do it now than later I suppose though, @helgi...

**Comment by helgi** [comment]
@sgoings agreed - just pointing out the likely error scenario when we effectively swap one project with another in the same git path

**Comment by bacongobbler** [comment]
Anyone feel like breaking stuff? When should we rip the band-aid? :hammer:

**Comment by mboersma** [comment]
*Before* beta? Seriously?

**Comment by slack** [comment]
We will make the call on Monday.

**Comment by mboersma** [comment]
> Before beta?

My apologies for getting worked up about this. If we can get 'er done, let's do it. Let's see where we are on Monday.

**Comment by arschles** [comment]
Note that the client has been moved to https://github.com/deis/workflow-cli. That repository is a work in progress...

**Comment by arschles** [comment]
[deis/workflow-cli](https://github.com/deis/workflow-cli) is now up & deploying to bintray. All related issues are now closed.

**Comment by bacongobbler** [comment]
if nobody else it tacking the deisci/controller job stuff, I'd be happy to tackle that.

**Comment by bacongobbler** [comment]
> fixup jenkins/travis to push to deisci/controller

done in deis/workflow#494, and the charts will now reference the component name as "controller" in deis/charts#153. Now all that's lefts is the holistic lift n' shift to deis/controller or deis/deis on the github side of things. There is also documentation that needs updating.

**Comment by bacongobbler** [comment]
Okay, I've filed a bunch of issues. To summarize:

https://github.com/deis/charts/issues/126
https://github.com/deis/charts/issues/155
https://github.com/deis/router/issues/141
https://github.com/deis/workflow-cli/issues/20
https://github.com/deis/workflow-cli/issues/21

Are some things that need to be discussed before I go further down the rabbit hole. The rest is mostly documentation, but these issues basically cover the architectural changes that require discussion.

**Comment by sgoings** [comment]
Superseded by 4962
