### ISSUE TITLE
[meta] Deis Workflow RC

### ISSUE THREAD

**Issue by slack** [deis/deis#4961]
This issue is currently a Work in Progress

[RC Issues Search](https://github.com/issues?q=is%3Aopen+user%3Adeis+user%3Ahelm+milestone%3Av2.0-rc1+sort%3Aupdated-desc)

### Security target
* [ ] All platform components run as non-root users (whenever possible)

### Test target
* [ ] load test: running for week (24/7) < 1% dropped requests
* [ ] load test: 1 deploy/minute across 5 independent applications
* [ ] workflow-e2e consistently green
* [ ] all 2.0 functionality covered with e2e test

### Scale target
* [ ] TBD

### Dogfooding target
* [x] production cluster provisioned
* [ ] slack.deis.io deployed
* [x] WFM Backend Deployed

### Documentation
* [ ] all workflow/component configuration documented

### Infrastructure
* [x] AWS: zero running to recovery from s3 storage (in us-east-1 and us-west-2)
* [x] GKE: zero running to recovery from GCS (compat mode)

### Operations
* [ ] resource requirements (cpu/mem) declared for workflow components

### UX
* [x] Object Storage Cleanup: deis/deis#4966

**Comment by arschles** [comment]
Also note object storage configuration: https://github.com/deis/deis/issues/4966

**Comment by arschles** [comment]
Nevermind, I just saw it under `ux`...

**Comment by vdice** [comment]
@slack can this ticket move to the `v2.0` milestone?

**Comment by slack** [comment]
Sure.

**Comment by slack** [comment]
Actually, I'll just close this.
