### ISSUE TITLE
[meta] Deis v2 Beta Final Push

### ISSUE THREAD

**Issue by sgoings** [deis/deis#4962]
This is a toplevel issue to track the things that we need to do before we can ship Deis v2 Beta:

### Project Release

- [x] immutable tag publishing
  - [x] [router](https://github.com/deis/router/issues/145)
  - [x] [registry](https://github.com/deis/registry/issues/28)
  - [x] [postgres](https://github.com/deis/postgres/issues/64)
  - [x] [dockerbuilder](https://github.com/deis/dockerbuilder/issues/32)
  - [x] [slugrunner](https://github.com/deis/slugrunner/issues/20)
  - [x] [slugbuilder](https://github.com/deis/slugbuilder/issues/36)
  - [x] [minio](https://github.com/deis/minio/issues/83)

### Project Organization (began from https://github.com/deis/deis/issues/4952)

- [x] rename deis/workflow -> deis/controller
  - [x] https://github.com/deis/charts/pull/157 (orig. issue: https://github.com/deis/charts/issues/126)
  - [x] https://github.com/deis/charts/issues/155
- [x] rename deis/docs-v2 -> deis/workflow
  - ensure we have links to all components from README

### Project Quality

- [x] get e2e tests green
- [x] fix/address https://github.com/deis/controller/issues/522
- [x] [Document how to configure the database to backup to S3](https://github.com/deis/workflow/issues/95) (fixed by https://github.com/deis/workflow/pull/100)
- [x] [Document what secrets to change in order to change credentials](https://github.com/deis/workflow/issues/101) (fixed by https://github.com/deis/workflow/pull/104)
- [x] [Document how to configure the `minio-user` secret for the controller](https://github.com/deis/workflow/issues/97) (fixed by https://github.com/deis/workflow/pull/102)
- [x] README updates
  - take out cookie cutter text
  - take out "danger: alpha" text + references
  - [A template](https://github.com/deis/workflow/pull/500) courtesy of @arschles 
  - Repos:
    - [x] [builder](https://github.com/deis/builder) (https://github.com/deis/builder/pull/256)
    - [x] [controller](https://github.com/deis/controller) (https://github.com/deis/controller/pull/500)
    - [x] [postgres](https://github.com/deis/postgres) (https://github.com/deis/postgres/pull/68)
    - [x] [router](https://github.com/deis/router) (https://github.com/deis/router/pull/147)
    - [x] [registry](https://github.com/deis/registry) (https://github.com/deis/registry/pull/29)
    - [x] [minio](https://github.com/deis/minio) (https://github.com/deis/minio/pull/84)
    - [x] [monitor](https://github.com/deis/monitor) (https://github.com/deis/monitor/pull/75)
    - [x] [dockerbuilder](https://github.com/deis/dockerbuilder) (https://github.com/deis/dockerbuilder/pull/35)
    - [x] [slugbuilder](https://github.com/deis/slugbuilder) (https://github.com/deis/slugbuilder/pull/38)
    - [x] [slugrunner](https://github.com/deis/slugrunner) (https://github.com/deis/slugrunner/pull/22)
    - [x] [workflow-e2e](https://github.com/deis/workflow-e2e) (https://github.com/deis/workflow-e2e/pull/113)
    - [x] [workflow](https://github.com/deis/workflow) (https://github.com/deis/workflow/pull/107)
    - [x] [charts](https://github.com/deis/charts) (https://github.com/deis/charts/pull/172)

### Last Second Changes:
- [x] [mock the k8s API interactions and remove Container model](https://github.com/deis/controller/pull/497)

### Release Tasks
- [ ] Ensure getting started docs will point to install workflow-beta1 (https://github.com/deis/workflow/issues/106)
- [x] Retag git-sha docker images to deis org + tag with v2.0.0-beta1
  - e.g. quay.io/deis/controller:v2.0.0-beta1
- [x] Tag all components' git repositories with ^^ sha as v2.0.0-beta1
  - e.g. controller.git tag == v2.0.0-beta1
- [x] [Cut workflow-beta1 chart](https://github.com/deis/charts/issues/167)
