### ISSUE TITLE
Tasklist: Deis is ops/HA-ready

### ISSUE THREAD

**Issue by carmstrong** [deis/deis#984]
- [x] Support for multiple routers (#969)
- [x] Basic upgrading documentation (#1012)
- [x] All Deis requests should flow through a router (#535)
- [x] Stateful components don't backup or share data between hosts (#1038)
- [x] Parameterize container versions in unit files (#1023)
- [x] Rethink ops/infrastructure documentation (#921)
- [x] deisctl provision utility (#1238)
- [x] controller reloads config on restart (#1928)
- [x] backing store component (#1910)
- [x] Back deis-registry with the deis-store blob store (#1906)
- [x] database backups and WAL log shipping (#1385)
- [x] Decouple all Deis components (#985)
- [x] Deis upgrader (#2172)
- [x] Platform logging documentation (#980)
- [x] Platform monitoring documentation (#981)
- [x] Backup/restore documentation (#2104)

Some additional discussion in #874
